### ISSUE TITLE
Query Explorer query execution error

### ISSUE THREAD

**Issue by oscarspaz** [googleanalytics/ga-dev-tools#289] opened 2017-04-07 14:27 UTC
Query will not run because of a javascript error. Attached screenshot.

> Uncaught TypeError: window.google.load is not a function

![2017-04-07_09h24_23](https://cloud.githubusercontent.com/assets/1151899/24804555/6b5a6b60-1b74-11e7-81ec-38cc4d72f22f.png)

**Comment by mcohoon** [comment] 2017-04-07 15:01
Duplicate of [issue 288](https://github.com/googleanalytics/ga-dev-tools/issues/288)

**Closed by mcohoon** 2017-04-07 15:01 UTC
Labels: duplicate
