### ISSUE TITLE
Disabling third-party cookies and data causes infinite loading

### ISSUE THREAD

**Issue by StephanBijzitter** [googleanalytics/ga-dev-tools#285] opened 2017-03-27 16:47 UTC
This is a follow-up on #284.

```
XHR finished loading: GET "https://content.googleapis.com/discovery/v1/apis/analytics/v3/rest?fields=k…Url%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid&pp=0".
zu @ cb=gapi.loaded_0:121
n @ cb=gapi.loaded_0:121
Cu @ cb=gapi.loaded_0:121
(anonymous) @ cb=gapi.loaded_0:122
g @ cb=gapi.loaded_0:77
c @ cb=gapi.loaded_0:73
cb=gapi.loaded_0:69 Uncaught Object {error: "idpiframe_initialization_failed", details: "Failed to read the 'localStorage' property from 'Window': Access is denied for this document."}
(anonymous) @ cb=gapi.loaded_0:69
common.js:6 Uncaught TypeError: Cannot read property 'name' of null
    at m (common.js:6)
    at common.js:6
```
This is using Opera, with the following options ticked:
Allow local data to be set (recommended)
Block third-party cookies and site data

**Comment by philipwalton** [comment] 2017-03-28 01:29
Closing to keep this discussion in #284 as these have the same root cause.

**Closed by philipwalton** 2017-03-28 01:29 UTC

**Comment by Flimm** [comment] 2017-03-30 10:57
Just to add another data-point, I also experienced a similar issue when setting this parameter in Firefox:

- Preferences -> Privacy -> Accept cookies from sites (checked)
- Preferences -> Privacy -> Accept third-party cookies "From Visited"

With "From Visited", I experience this error in the console:

> uncaught exception: [object Object]

And the page looks like it never finishes loading.

Changing "From Visited" to "Always" fixes this problem.

**Comment by philipwalton** [comment] 2017-03-30 16:22
Please keep the discussion in #284. I'll update the title of that issue to use the term third-party cookie.
