### ISSUE TITLE
Hit-builder broken in Canary 54.0.2827.0

### ISSUE THREAD

**Issue by 75lb** [googleanalytics/ga-dev-tools#215] opened 2016-08-12 21:07 UTC
getting this error in Canary
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at x.pa (https://ssl.gstatic.com/accounts/o/2911098322-idpiframe.js:6:334)
    at P.h.start (https://ssl.gstatic.com/accounts/o/2911098322-idpiframe.js:42:293)
    at Object.rb [as startIdpIFrame] (https://ssl.gstatic.com/accounts/o/2911098322-idpiframe.js:76:713)
    at https://accounts.google.com/o/oauth2/iframe:1:414
```

**Comment by philipwalton** [comment] 2016-08-12 21:32
I can't reproduce this, and from that stack trace it looks like its Google OAuth code, which isn't part of the Demos & Tools site.

**Comment by 75lb** [comment] 2016-08-12 21:39
i tried signing out of Google and disabling extensions, no joy.. For now I can use Hit Builder in Chrome stable.

<img width="1280" alt="screen shot 2016-08-12 at 22 36 37" src="https://cloud.githubusercontent.com/assets/1247980/17637715/5732cd96-60dd-11e6-9dfc-2e26e9ba7ae1.png">

**Comment by philipwalton** [comment] 2016-08-12 22:01
Very strange. I'm using Chrome 54.0.2827.0 canary (64-bit) as well, and I don't get any errors.

**Comment by 75lb** [comment] 2016-08-12 22:27
how odd.. i tried clearing storage in the DevTools Application tab and loading in an incognito tab - same issue.. it works in FF 50.0a2 (developer edition).. i'm on a Macbook Pro with the latest OS (10.11.6).. 

Accessing `window.localStorage` from the `top` context works fine: 
<img width="1028" alt="screen shot 2016-08-12 at 23 25 31" src="https://cloud.githubusercontent.com/assets/1247980/17638734/22523b00-60e4-11e6-8a73-998226f060d0.png">

But fails from the `ssl frame` context. 
<img width="1042" alt="screen shot 2016-08-12 at 23 25 43" src="https://cloud.githubusercontent.com/assets/1247980/17638754/40bea5a6-60e4-11e6-8493-ed04a27a39f7.png">

I've got a feeling this is a browser regression and will soon go away.

**Comment by philipwalton** [comment] 2016-10-28 23:57
Closing since this issue isn't happening in the released Chrome 54.

**Closed by philipwalton** 2016-10-28 23:57 UTC
