### ISSUE TITLE
API tool won't run reports!

### ISSUE THREAD

**Issue by lmoscone** [googleanalytics/ga-dev-tools#42] opened 2015-03-10 14:00 UTC
All of a sudden, none of my reports will run when clicking Add-Ons > Google Analytics > Run Reports, on any accounts where I have reports set up. Happening to one other coworker, while the other two are fine (on PC using Chrome or Firefox for the broken ones, one of the people who has it working is using the same, one is on a Mac).

**Comment by philipwalton** [comment] 2015-03-10 18:31
Closing as a duplicate of #43.

The easiest solution at the moment is to upgrade to Chrome 41.

**Closed by philipwalton** 2015-03-10 18:31 UTC
