### ISSUE TITLE
Page loading issue across website

### ISSUE THREAD

**Issue by Arcaelyx** [googleanalytics/ga-dev-tools#539] opened 2020-08-09 16:52 UTC
Many pages are stuck loading and this problem has persisted for weeks now. I've tested it out on multiple computers, it's essentially the same loading problem as issue #515. It can be found on these pages:

https://ga-dev-tools.appspot.com/account-explorer/
https://ga-dev-tools.appspot.com/query-explorer/
https://ga-dev-tools.appspot.com/hit-builder/
https://ga-dev-tools.appspot.com/request-composer/

**Comment by diminishedprime** [comment] 2020-08-10 16:39
Can you add some details on the issue?

What OS/Browsers are you using, etc. 

I'm not able to reproduce this error (all of these pages load correctly for me, both when logged in and logged out). 

Can you make sure you can reproduce the error in an incognito window with no extensions loaded?

**Comment by diminishedprime** [comment] 2021-06-03 22:18
This issue should be resolved in the newest version of the site: https://ga-dev-tools.web.app/

**Closed by diminishedprime** 2021-06-03 22:18 UTC
