### ISSUE TITLE
Custom dimensions still not populating

### ISSUE THREAD

**Issue by robflaherty** [googleanalytics/ga-dev-tools#704] opened 2021-08-30 11:29 UTC
**Describe the bug**
90% of the time Custom Dimensions do not populate in the dimensions field. 

**To Reproduce**
1. Type the name of the custom dimension in the Dimensions field
2. It doesn't appear as a type-ahead option.

**Desktop (please complete the following information):**
- Chrome Version 92.0.4515.159

**Comment by diminishedprime** [comment] 2021-09-02 15:45
duplicate of #705

**Closed by diminishedprime** 2021-09-02 15:45 UTC
