### ISSUE TITLE
Query Explorer Not Working

### ISSUE THREAD

**Issue by D6Analytics** [googleanalytics/ga-dev-tools#462] opened 2019-12-05 17:18 UTC
Hello,

The Google Analytics query explorer is currently malfunctioning. When trying to choose a metric or dimension, the drop down presents "No matches found."

I've attached a picture for your reference.

<img width="476" alt="Annotation 2019-12-05 121730" src="https://user-images.githubusercontent.com/58566313/70257909-41b30180-1759-11ea-9dcc-221d6d36b576.png">

Please advise.

Thank you!

**Comment by pfrisella** [comment] 2019-12-05 17:21
Duplicate of #461

**Closed by pfrisella** 2019-12-05 17:21 UTC
