### ISSUE TITLE
UA Query Explorer Issues

### ISSUE THREAD

**Issue by benclaflin** [googleanalytics/ga-dev-tools#744] opened 2021-10-26 20:11 UTC
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
You can no longer search in the field by text title. For instance, if I have a segment called "All New Users", if I type "All New Users" into the Segment field the aforementioned segment won't come up. Instead it searches for the Segment ID (like: gaid::0czqR4DR6-CP7cP6Ux4-gg, etc). This also applies to Metrics, Dimensions, and Filters. It makes the search fields essentially useless.

**To Reproduce**
1. https://ga-dev-tools.web.app/query-explorer/
2. Click on any of the Metrics/Dimension/Filter/Segment fields and try to search for something by title (for instance, search the Metrics field for "Conversion Rate" and you'll get zero results)

**Expected behavior**
You should be able to search by the title of the field. This is how the query explorer worked until it was relaunched a few months ago. 

**Screenshots**
![example](https://user-images.githubusercontent.com/89115913/138953397-281c2f99-235f-434e-98c6-fe4acb49cfc3.png)

**Additional context**
This problem began with the relaunch of the query explorer (when it moved from https://ga-dev-tools.appspot.com/query-explorer/ to https://ga-dev-tools.web.app/query-explorer/

**Comment by diminishedprime** [comment] 2021-11-03 17:30
Duplicate of #738

**Closed by diminishedprime** 2021-11-03 17:30 UTC
Labels: feature request
