### ISSUE TITLE
Can't shorten link in Google Campaign URL Builder

### ISSUE THREAD

**Issue by CaggenPL** [googleanalytics/ga-dev-tools#950] opened 2022-07-20 08:22 UTC
**What page is this happening on**
https://ga-dev-tools.web.app/campaign-url-builder/

**Describe the bug**
Not possible to shorten the created url.

**To Reproduce**
1. Fill out all required fields.
2. Click on 'Shorten link'
3. See error

**Expected behavior**
A shortened link should be generated, but nothing happens. Button is visibly pressed, but no link is generated.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ikuleshov** [comment] 2022-07-21 01:54
Hello,

The issue does not seem to be reproducible. To ensure the problem is not related to your browser environment, could you kindly open a new Incognito browser window and try to shorten the URL again. Closing the issue for the time being, feel free to reopen if the problem persists.

**Closed by ikuleshov** 2022-07-21 01:54 UTC

**Comment by CaggenPL** [comment] 2022-07-21 08:09
> Hello,
> 
> The issue does not seem to be reproducible. To ensure the problem is not related to your browser environment, could you kindly open a new Incognito browser window and try to shorten the URL again. Closing the issue for the time being, feel free to reopen if the problem persists.

Hi,

Works fine in incognito, thank you!
