### ISSUE TITLE
UID vs CID in measurement protocol

### ISSUE THREAD

**Issue by tommybravo** [googleanalytics/ga-dev-tools#369] opened 2018-04-26 15:27 UTC
When I'm using the Hit Builder tools, it validates a request if it has a UID parameter, but does not have a CID parameter. Requests without CID, however, do not show up in Analytics after hitting the "Send hit to analytics" button.

Example: v=1&t=event&tid=UA-xxx&uid=13717421&ec=email&ea=open
Validates in Hit Builder (and at the api endpoint /debug/collect).
No sign of the event in Analytics.
Example2: v=1&t=event&tid=UA-xxx&cid=555&uid=13717421&ec=email&ea=open
Validates in both Hit Builder and records in Analytics.

**Comment by philipwalton** [comment] 2018-04-26 17:50
@Lucretiel can you confirm? If so it might also be worth filing a bug internally against the [Measurement Protocol Validation Service](https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits).

**Comment by tommybravo** [comment] 2018-04-26 20:09
For what it's worth: The validation service is right, as the UID "field is required if User ID (uid) is not specified in the request", according to measurement protocol reference. The error seems to be on the Analytics end.

**Comment by pif** [comment] 2018-11-05 13:38
I observed the same behaviour when I was trying to setup updates to User's Custom Dimension field from the backend servers. Was this addressed in any way?

**Comment by mrwwalmsley** [comment] 2019-06-21 00:21
My experience was that if you leave out the CID but set UID, then the hit won't show up in a regular analytics view, but will show up in a users view.

So UID makes the hit get recorded in user view.
CID makes the hit get recorded in regular view.

**Comment by millionbonus** [comment] 2019-09-17 10:53
You have to turn on the "Show User-ID Reports" option while you are creating the view.
Only the view which enabled the option shows user-id data.

![Snipaste_20190917_183619](https://user-images.githubusercontent.com/705574/65035588-29162500-d97c-11e9-91bc-3080847d631f.png)

**Comment by MatthewFin** [comment] 2019-11-26 12:39
Is there any update on this?

I'm having the same issue where hits without a "cid" parameter, but with the "uid" parameter do not show up at all in analytics (in either a Raw view, or a User ID view).  This basically makes tracking events from our backend when we don't know a user's client id impossible.

Any help would be appreciated.

**Comment by diminishedprime** [comment] 2020-06-12 18:11
This is the intended behavior.

**Closed by diminishedprime** 2020-06-12 18:11 UTC
